### ISSUE TITLE
Support ddev share for Magento Projects

### ISSUE THREAD

**Issue by dermatz** [OpenForgeProject/ddev-woodoo-buildtools-magento#26]
- use ddev share with automatic config import for ngrok (free) domains

**Comment by dermatz** [comment]
Investigate for a possibility to crab/get the ngrok forward-url and update local magento base url

**Comment by rfay** [comment]
Just a note that `ddev share` is just a trivial wrapper on ngrok, which you know. A custom command `ddev magshare` would be easy to create. Also, the free `cloudflared` is a good competitor, as demonstrated in  https://stackoverflow.com/a/78744731/215713

**Comment by dermatz** [comment]
Thanks @rfay - i will take a look into this

**Comment by dermatz** [comment]
Will be supported in other module (coming soon)
